### ISSUE TITLE
Add a bower.json file

### ISSUE THREAD

**Issue by halloffame** [shutterstock/rickshaw#361]
Installing rickshaw with bower includes everything. It would be nice if you added a bower.json file to ignore all but the source files.

http://bower.io/

**Comment by findkiko** [comment]
What's the proper way to have these scripts injected by bower/gulp? I created a bower.json file manually to fix my app before finding this closed issue. I'm confused now what I should have done if anything.

**Comment by aendrew** [comment]
@findkiko Bower is being used increasingly less in frontend development due to the advent of libraries like Webpack and Browserify, which bundle dependencies effectively and remove reliance on attaching dependencies to the browser global object. While I'd recommend to go this route, if you're using Wiredep or main-bower-files, you can still install any dependency via GitHub shortname (I.e., `bower install shutterstock/rickshaw`) and then specifying the library's main entry points in your `bower.json` file. See docs for [bower-main-files](https://github.com/ck86/main-bower-files#overrides-options) and [wiredep](https://github.com/taptapship/wiredep#bower-overrides).

**Comment by findkiko** [comment]
OK, thanks for the pointer. I'm modifying an existing code-base that uses wiredep so did end up figuring out the solution you mention eventually (adding a main clause).
